from selenium.webdriver.common.by import By


class PimPageLocators:
    configuration = (By.XPATH, "//span[@class='oxd-topbar-body-nav-tab-item'']")
    add_employee = (By.XPATH, "//a[@href='#' and text()='Add Employee']")
    employee_list = (By.XPATH, "//a[@href='#' and text()='Employee List']")
    Reports = (By.XPATH, "//a[@href='#' and text()='Reports']")
    firstName = (By.XPATH, "//input[@name='firstName']")
    middleName = (By.XPATH, "//input[@name='middleName']")
    lastName = (By.XPATH, "//input[@name='lastName']")
    employee_full_name = (By.XPATH,"//label[normalize-space()='Employee Name']/ancestor::div[contains(@class,'oxd-input-group')]//input")
    employee_id = (By.XPATH, "//label[normalize-space()='Employee Id']/ancestor::div[contains(@class,'oxd-input-group')]//input")
    createLoginDetailCheckbox = (By.XPATH, "//p[normalize-space()='Create Login Details']/ancestor::div[contains(@class,'oxd-form-row user-form-header')]//span")
    userName = (By.XPATH, "//label[normalize-space()='Username']/ancestor::div[contains(@class,'oxd-input-group')]//input")
    passWord = (By.XPATH, "//label[normalize-space()='Password']/ancestor::div[contains(@class,'oxd-input-group')]//input")
    confirmPassword = (By.XPATH, "//label[normalize-space()='Confirm Password']/ancestor::div[contains(@class,'oxd-input-group')]//input")
    saveButton = (By.XPATH, "//button[@type='submit']")
    cancelButton = (By.XPATH, "//button[@type='button' and normalize-space()='Cancel']")
    status_enabled = (By.XPATH, "//input[@type='radio' and @value='1']")
    status_disabled = (By.XPATH, "//label[normalize-space()='Disabled']")
    employee_name_listPage = (By.XPATH, "//h6[@class='oxd-text oxd-text--h6 --strong']")
    employee_id_listPage = (By.XPATH, "//label[normalize-space()='Employee Id'] /ancestor::div[contains(@class,'oxd-input-group')]//input[contains(@class,'oxd-input')]")
    search_button = (By.XPATH, "//button[normalize-space()='Search']")
    select_employee_zero = (By.XPATH, "//input[@type='checkbox' and @value='0']/parent::label")
    delete_employee_button = (By.XPATH, "//button[@type='button' and @class='oxd-button oxd-button--medium oxd-button--label-danger orangehrm-horizontal-margin']")
    yes_deleted_button = (By.XPATH, "//button[@type='button' and @class='oxd-button oxd-button--medium oxd-button--label-danger orangehrm-button-margin']")
    no_records_found = (By.XPATH, "//span[normalize-space()='No Records Found']")
